[tool.ruff]
select = ["E", "F", "I", "N", "RSE", "RET", "TCH", "ARG", "RUF"]
line-length = 101
exclude = [
    "db1/_protos/"
]

[tool.mypy]
python_version = 3.9
ignore_missing_imports = true
exclude = "build/"

[tool.black]
line-length = 101
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | db1/_protos
  )/
)
'''