# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serializer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10serializer.proto"\xd6\x02\n\x05Value\x12\x19\n\x04type\x18\x01 \x01(\x0e\x32\x0b.Value.Type\x12\x0e\n\x06int64_\x18\x02 \x01(\x03\x12\x0e\n\x06\x66loat_\x18\x03 \x01(\x02\x12\x0f\n\x07string_\x18\x04 \x01(\t\x12\r\n\x05\x62ool_\x18\x05 \x01(\x08\x12\x0e\n\x06\x62ytes_\x18\x06 \x01(\x0c\x12\x14\n\x04list\x18\x07 \x03(\x0b\x32\x06.Value\x12\x13\n\x04\x64ict\x18\x08 \x01(\x0b\x32\x05.Dict\x12\x19\n\x07ndarray\x18\t \x01(\x0b\x32\x08.NDArray\x12\x1e\n\ndata_frame\x18\n \x01(\x0b\x32\n.DataFrame"|\n\x04Type\x12\x08\n\x04NONE\x10\x00\x12\n\n\x06INT64_\x10\x01\x12\n\n\x06\x46LOAT_\x10\x02\x12\x0b\n\x07STRING_\x10\x03\x12\t\n\x05\x42OOL_\x10\x04\x12\n\n\x06\x42YTES_\x10\x05\x12\x08\n\x04LIST\x10\x06\x12\x08\n\x04\x44ICT\x10\x07\x12\x0b\n\x07NDARRAY\x10\x08\x12\r\n\tDATAFRAME\x10\t"6\n\x07NDArray\x12\x0e\n\x06\x62ytes_\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\r\x12\x0c\n\x04type\x18\x03 \x01(\t",\n\x04\x44ict\x12\x0c\n\x04keys\x18\x01 \x03(\t\x12\x16\n\x06values\x18\x02 \x03(\x0b\x32\x06.Value"S\n\tDataFrame\x12\x15\n\x05index\x18\x01 \x01(\x0b\x32\x06.Value\x12\x17\n\x07\x63olumns\x18\x02 \x01(\x0b\x32\x06.Value\x12\x16\n\x06values\x18\x03 \x03(\x0b\x32\x06.Valueb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "serializer_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _VALUE._serialized_start = 21
    _VALUE._serialized_end = 363
    _VALUE_TYPE._serialized_start = 239
    _VALUE_TYPE._serialized_end = 363
    _NDARRAY._serialized_start = 365
    _NDARRAY._serialized_end = 419
    _DICT._serialized_start = 421
    _DICT._serialized_end = 465
    _DATAFRAME._serialized_start = 467
    _DATAFRAME._serialized_end = 550
# @@protoc_insertion_point(module_scope)
