name: Test

on: [push, pull_request]

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install -r requirements_dev.txt
        pip install types-requests
        pip install types-protobuf
    - name: Type check with mypy
      run: |
        mypy .
    - name: Lint with Ruff
      run: |
        ruff check .
    - name: Test with pytest
      run: |
        pytest -vv -s ./tests/test_item.py
